Rebuild libatomic for riscv64
libatomic shipped with stage3 is for x86_64 causing issues with
undefined symbols (e.g. swig package).

    /usr/lib64/libgcc_s.so: undefined reference to `__atomic_fetch_add_2'

The patch cross-compiles libatomic for riscv64 in hope to finally
solve undefined reference issues.

Signed-off-by: David Abdurachmanov <david.abdurachmanov@gmail.com>